// Objective-C API for talking to github.com/themihai/testios/client Go package.
//   gobind -lang=objc github.com/themihai/testios/client
//
// File is generated by gobind. Do not edit.

#ifndef __Client_H__
#define __Client_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* ClientStart(void);

FOUNDATION_EXPORT NSString* ClientStop(void);

#endif
